### ISSUE TITLE
10.11.6 + swift3

### ISSUE THREAD

**Issue by haohao110** [music4kid/EasyCode-Xcode#4]
10.11.6 + swift3可以用吗

**Comment by music4kid** [comment]
swift暂时还不行，不过可以自己fork后修改，修改配置文件就可以了。

**Comment by haohao110** [comment]
@music4kid  不会...希望出个支持swift的

**Comment by music4kid** [comment]
好的，后面我出个图像编辑界面。

**Comment by haohao110** [comment]
@music4kid 666

**Comment by music4kid** [comment]
新增了图形编辑界面，可以自己添加Swift了。

**Comment by haohao110** [comment]
@music4kid  你好啊,那个git上的代码我下载以后,run的时候有错,于是我就在appstore上下载了,但是xcode的editor并没有ec这个选项快捷键也搜索不到easy

**Comment by haohao110** [comment]
@music4kid xcode重启也没有效果啊

**Comment by haohao110** [comment]
弄好了
